export const ExportEngine = {
  copyToClipboard(text, onComplete) {
    navigator.clipboard.writeText(text)
      .then(() => {
        if (onComplete) onComplete(true);
      })
      .catch(err => {
        console.error('Copy failed:', err);
        if (onComplete) onComplete(false);
      });
  },

  downloadMarkdownNotes(data) {
    if (!data) return;
    
    let md = `# CodeMentor Study Notes: ${data.title} (${data.difficulty})\n\n`;
    md += `## Pattern\n${data.pattern}\n\n`;
    md += `## Acceptance Rate\n${data.acceptanceRate}\n\n`;
    md += `## Example Companies\n${data.companies.join(', ')}\n\n`;
    
    // Clean up HTML tags from markdown text export
    const cleanHTML = (html) => html.replace(/<br>/g, '\n').replace(/<[^>]*>/g, '');
    
    md += `## 1. Problem Breakdown\n${cleanHTML(data.analysis)}\n\n`;
    md += `## 2. Strategy & Pattern Insight\n${cleanHTML(data.strategy)}\n\n`;
    md += `## 3. Complexity Analysis\n`;
    md += `- Time Complexity: ${data.complexity.time} (Alternative: ${data.complexity.altTime})\n`;
    md += `- Space Complexity: ${data.complexity.space} (Alternative: ${data.complexity.altSpace})\n\n`;
    
    md += `## 4. Optimal Python Solution\n\`\`\`python\n${data.code}\n\`\`\`\n\n`;
    
    md += `## 5. Line-by-Line Explanation\n`;
    data.explanation.forEach(item => {
      md += `- **Line ${item.line}**: ${item.text}\n`;
    });
    md += `\n`;
    
    md += `## 6. Edge Cases Verified\n`;
    data.edgeCases.forEach(item => {
      md += `- [x] **Input**: \`${item.input}\` → **Result**: ${item.result}\n`;
    });
    md += `\n`;
    
    md += `## 7. Common Pitfalls to Avoid\n`;
    data.commonMistakes.forEach(item => {
      md += `### ${item.title}\n${item.p}\n\n`;
    });
    
    md += `## 8. Interview Follow-Ups\n`;
    data.followUps.forEach(item => {
      md += `**Q: ${item.q}**\n*A: ${item.a}*\n\n`;
    });
    
    md += `---\n*Generated by CodeMentor. Stop memorizing. Start recognizing patterns.*`;
    
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title.toLowerCase().replace(/\s+/g, '-')}-study-notes.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
};
